### ISSUE TITLE
Nested AsyncComponents not resolved server-side

### ISSUE THREAD

**Issue by cpeddecord** [ctrlplusb/react-async-component#21]
Thanks for the awesome library! I can't tell if I'm doing something wrong or not, but I can't seem to resolve nested components. Walking the element tree after passing through `withAsyncComponents` server-side describes nested async components as promises as yet unresolved:

```
{ path: '/test/foo',
  component:
   { [Function: AsyncComponent]
     childContextTypes: { asyncComponentsAncestor: [Object] },
     contextTypes: { asyncComponents: [Function: bound checkType] },
     displayName: 'AsyncComponent' },
  },
}
```

The tree could be described as thus:

```
// in routes.js
const baseTestRoute = (
  <Route
    path={'/test'}
    component={createAsyncComponent({
      resolve: () => import('./routes/NestedTestRoute'),
    })
    }
  />
);

// in ./routes/NestedTestRoute.js
export default function NestedTestRoute({ match }) {
  return (
    <Switch>
      <Route path={match.url} exact component={() => <h1>renders just fine, hooray!</h1>} />
      <Route
        path={`${match.url}/foo`}
        component={createAsyncComponent({
          resolve: () => import('./DeeplyNestedRoute'),
          Loading: () => <h1>this displays on the server</h1>,
        })}
      />
    </Switch>
  );
}

// in DeeplyNestedRoute.js
export default function DeeplyNestedRoute({ match }) {
  return (
      <Route path={`${match.url}/bar`} component={SomeComponentThatDoesNotRender} />
  );
}
```

If you need me to stand up a small application demonstrating the problem, I can definitely do as such.

**Comment by ctrlplusb** [comment]
Hey @cpeddecord 

Sorry just a quick one from me, but hopefully this helps.

I think this may be a side effect of you dynamically creating async component instances.  Try lifting your `createAsyncComponent(...` calls to a place where they are statically bound, i.e. outside of the body of a function.

Internally I have to try and keep some sort of identifier going so that I can know which async component instances get rendered.  With dynamic creation this number will keep ticking and I won't be able to marry up the instances for the resulting render within the `withAsyncComponents` handler.

**Comment by cpeddecord** [comment]
@ctrlplusb thanks for the note! I'll give it a try and see if I can't get it working :)

**Comment by ctrlplusb** [comment]
Hey @cpeddecord 

I have been working on a new version of this lib and during the refactor I think I may have spotted a bug that could lead to the behaviour you described.  I think I have it fixed in the `next` branch.  Don't use this branch yet though as it is in active development.  But I thought I would let you know in the interim.

**Comment by ctrlplusb** [comment]
Fixed in the alpha release. 😊

**Comment by cpeddecord** [comment]
@ctrlplusb yaay

**Comment by ctrlplusb** [comment]
A word of warning though, don't use as of yet.  I am still doing the rounds on it. :)

**Comment by dehypnosis** [comment]
I got a problem similar to cepddecord's one.

need to make dynamic routes likes `/posts/:id`. and also need to check the existence of post#id before component rendered.
works well in client, but serverside just show loading component.

here is a snippet
```js
function RoutedAsyncComponent({Component, resolver, routeProps, routerProps}) {
  const { user } = routeProps;
  const { match } = routerProps;

  const AsyncComponent = asyncComponent({
    resolve: () => {
      return resolver(user, match.params)
        .then(resolved => () => <Component resolved={resolved} {...routeProps} {...routerProps} />)
        .catch(err => () => <h1>Error</h1>)
    },
    LoadingComponent: () => <h1>Loading</h1>,
  });
  return <AsyncComponent />
}
```

anyway i just wanna ask you that can i use the next branch right in production now?
