### ISSUE TITLE
Consider Changing Double-Mount via prop?

### ISSUE THREAD

**Issue by bradennapier** [ctrlplusb/react-async-component#9]
Might be interesting to allow components to provide a prop to override the default behavior.  For example, if some components conduct actions within their ```componentWillMount``` function that we don't want the server to do and/or don't want to occur twice, we can override it by providing something like ```asyncComponentWillMount``` or something similar.  If not provided, default behavior applies.

**Comment by ctrlplusb** [comment]
Out of interest sake what are the type of things you are adverse to happen again within componentDidMount?  Are you doing side effects?

**Comment by bradennapier** [comment]
One thing I have noticed happening most likely due to this effect is that since everything is mounted, unmounted, then remounted - items with css transitions will sometimes act oddly.  One example is when I mount an item that starts with an opacity of 0 but will then fade in.  In this case the item seems to mount with 100% opacity, goes to 0, then starts fading in again.

I conduct almost 100% of my side effects and logic within the the saga processes so other than that is also just due to it feeling wasteful but I could be incorrect in my thinking there.

**Comment by ctrlplusb** [comment]
Hmmm, yeah, I think this just may be a case of misunderstanding by yourself. The "double mount" should only occur on the server and shouldn't affect any browser side rendering.

Here is the full workflow on the server:

 1. You create an element representing your application.
    ```jsx
    const app = <App />
    ```
    Remember, the above results in an object tree structure that describes to React what needs to be rendered. e.g.
    ```js
    {
      type: 'div',
      props: {
        children: [
          {
            type: 'h1',
            props: {
              children: 'Hello World!'
            }
          },
          {
            type: AsyncComponent,
          }
        ]
      }
    }
    ```
 2. You provide this element to `withAsyncComponents` so that we can determine if there are `AsyncComponent` instances that need to be resolved prior to you calling render.
    ```js
    withAsyncComponents(app)
    ```
    The way this works is that it has to iterateThis walks the element tree, when it find an element whose type is a Component it has to create an instance of the Component so that we can call it's `render` method and get back it's child elements so that we can continue walking. As it is completely acceptable for Component designers to initialise the Component's state within `componentWillMount` we need to call this as their render method could be depending on some of this state.
    This process will then find any `AsyncComponent` instances and will only parse these based on the `ssrMode` configuration value you used in the `createAsyncComponent` helper.  We keep a registry of the resolved Component for each `AsyncComponent` that was parsed and then we throw everything else away. i.e. no rendering information in this step is stored.
  3. You get back a `Promise` from the `withAsyncComponents` that contains a decorated version of your application which contains a link to the resolved Components registry that was created in step 2. You then pass through the decorated version of your app to `ReactDOM.renderToString` and this becomes the response for your application.  It uses no state/data from the step 2 process, it will only immediately render any `AsyncComponent` instances for which there is a resolved Component reference in the `registry`.
    ```js
    withAsyncComponents(app).then(({ appWithAsyncComponents, state, STATE_IDENTIFIER }) => {
      const response = renderToString(appWithAsyncComponents);
    })
    ```

So technically we are calling the `componentWillMount` of your Components twice (in some cases) but it is throw away information for the first call, and is merely used to get the child element tree.  In no way do we use the render results from step 2 in the rendering of your application.

On the browser side the `componentWillMount` should only be called once.  If it gets called twice this is a bug, please report it.

Please let me know if this explanation is more clear.  I want to update the README to make this more clear to everyone.

**Comment by ctrlplusb** [comment]
> One thing I have noticed happening most likely due to this effect is that since everything is mounted, unmounted, then remounted - items with css transitions will sometimes act oddly. One example is when I mount an item that starts with an opacity of 0 but will then fade in. In this case the item seems to mount with 100% opacity, goes to 0, then starts fading in again.

We only do the previously described process on the server.  What you describe here sounds like a browser side interaction/bug.  If you are experiencing double mounts on the browser please do let me know.

**Comment by bradennapier** [comment]
Yes this is happening on the browser

**Comment by ctrlplusb** [comment]
Ah yes of course sorry. It will do it on the browser to resolve the same components that were on server. So it won't do a full tree walk in this case. Sorry I will update the docs with this part too.

**Comment by ctrlplusb** [comment]
But yes again to be clear. The component state shouldn't transfer from the first resolve parse to the actual render. So you shouldn't see any opacity flickering or whatever because no actual rendering occurs in the withAsyncComponents call

**Comment by bradennapier** [comment]
Yeah that is not what I am seeing.  I can clearly see the ENTIRE APP render then async components then it re renders based on logs

**Comment by bradennapier** [comment]
Gonna try to capture a screenshot of logs to show you

**Comment by ctrlplusb** [comment]
👌

**Comment by bradennapier** [comment]
Still working on getting better information and making sure it isn't something else.  Quick question in the meantime.  So using import would generally mean that webpack will code split that data?  For example, if I did something like:

```javascript
function* sagaImport(path) {
  const importPromise = new Promise(resolve => {
    import(`./${path}`)
      .then(module => {
        console.log('Module: ', module)
        resolve(module)
      })
  })
  const awaitPromise = () => Promise.resolve(importPromise),
        module       = yield call(awaitPromise)
  return module
}
```
